apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ysogpe5dd-nodejs 
  janus-idp.io/tekton: ysogpe5dd-nodejs
  backstage.io/kubernetes-id: ysogpe5dd-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ysogpe5dd-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  