apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ysogpe5dd-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ysogpe5dd-nodejs 
  name: ysogpe5dd-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ysogpe5dd-nodejs 
